# Generated by Django 5.0.6 on 2024-05-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
