# Generated by Django 5.0.6 on 2024-05-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
