# Generated by Django 5.0.6 on 2024-05-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
