# Generated by Django 5.0.6 on 2024-05-22 20:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('about_me', models.TextField(blank=True, max_length=1000, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_artisan', models.BooleanField(blank=True, default=0, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
