# Generated by Django 5.0.6 on 2024-05-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_profile_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expertise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
