# Generated by Django 5.0.6 on 2024-05-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hourly_rate',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
