# Generated by Django 5.0.6 on 2024-05-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, default='no data', max_length=1000, null=True),
        ),
    ]
