# Generated by Django 5.0.6 on 2024-05-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
