# Generated by Django 5.0.6 on 2024-05-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='Rabat', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='Morocco', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expertise',
            field=models.CharField(blank=True, default='no experience', max_length=100, null=True),
        ),
    ]
