# Generated by Django 5.0.6 on 2024-05-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_review_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile-photo.png', null=True, upload_to=''),
        ),
    ]
