# Generated by Django 5.0.6 on 2024-05-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expertise',
            field=models.CharField(blank=True, default='no job', max_length=100, null=True),
        ),
    ]
